name: Tests

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x 
      - run: dotnet build NamePrinter -f net6.0
      - run: dotnet test Tests -f net3.1
      - run: dotnet test Tests -f net5.0
      - run: dotnet test Tests -f net6.0
